name: marvel_comics
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: 2.0.3

dev_dependencies:
  build_runner: 2.1.11
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1
  freezed: 2.0.3+1

flutter:
  uses-material-design: true
